name: Update DockerHub Description

on: push

jobs:
  update-description:
    runs-on: self-hosted-amd64-1cpu
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import secrets
        uses: hashicorp/vault-action@v3
        id: secrets
        with:
          exportEnv: false
          url: ${{ secrets.VAULT_URL }}
          role: ${{ secrets.VAULT_ROLE }}
          method: kubernetes
          path: kubernetes-ci
          secrets: |
            kv-gitlab-ci/data/github/shared/dockerhub-creds user | DOCKERHUB_USER ;
            kv-gitlab-ci/data/github/shared/dockerhub-creds password | DOCKERHUB_PASSWORD ;

      - name: Set up secret file
        env:
          DEBUG_USER: ${{ steps.secrets.outputs.DOCKERHUB_USER }}
          DEBUG_PASSWORD: ${{ steps.secrets.outputs.DOCKERHUB_PASSWORD }}
        run: |
          echo $DEBUG_USER >> secrets.txt
          echo $DEBUG_PASSWORD >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2

#      - name: Update DockerHub Description
#        uses: peter-evans/dockerhub-description@v4
#        with:
#          username: ${{ steps.secrets.outputs.DOCKERHUB_USER }}
#          password: ${{ steps.secrets.outputs.DOCKERHUB_PASSWORD }}
#          repository: wallarm/gotestwaf
#          short-description: ${{ github.event.repository.description }}
#          readme-filepath: ./README.md
